services:
  counter_rust:
    build:
      context: ./counter

  counter_go:
    build:
      context: ./backend
  counter_svelte:
    build:
      args:
        - PUBLIC_GO_URL=https://${CADDY_DOMAIN}/api
        - PUBLIC_WS_URL=wss://${CADDY_DOMAIN}/api/ws
      context: ./frontend
