services:
  counter_rust:
    build:
      context: ./backend
  counter_svelte:
    build:
      args:
        - PUBLIC_BACKEND_URL=https://${CADDY_DOMAIN}/api
        - PUBLIC_WS_URL=wss://${CADDY_DOMAIN}/api/ws
      context: ./frontend
