services:
  go:
    image: blue-counter_go:latest
    networks:
      - counter_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    environment:
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - COUNTERS_TOPIC=${COUNTERS_TOPIC}
      - GO_PORT=${GO_PORT}
      - RUST_URL=http://${RUST_NAME}:${RUST_PORT}
      - SVELTE_URL=https://${CADDY_DOMAIN}

  svelte:
    image: blue-counter_svelte:latest
    networks:
      - counter_network
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s

  caddy:
    image: caddy:latest
    networks:
      - counter_network
    ports:
      - "80:80"
      - "443:443"
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
    environment:
      - CADDY_DOMAIN=${CADDY_DOMAIN}
      - GO_NAME=${GO_NAME}
      - GO_PORT=${GO_PORT}
      - SVELTE_NAME=${SVELTE_NAME}
      - SVELTE_PORT=${SVELTE_PORT}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - type: bind
        source: Caddyfile
        target: /etc/caddy/Caddyfile

networks:
  counter_network:
    driver: overlay
    attachable: true

volumes:
  caddy_data:
  caddy_config:

configs:
  caddy_config:
    file: Caddyfile
