{
 "title": "Real Time Voting",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Max Concurrent Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(concurrent_users{instance=\"rust:3000\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"pickone-metrics\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Users Ever",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "users" } },
   "targets": [
    {
     "expr": "total_users{job=\"pickone-metrics\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Concurrent Users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "users" } },
   "targets": [
    {
     "expr": "concurrent_users{job=\"pickone-metrics\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Votes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "votes" } },
   "targets": [
    {
     "expr": "votes{instance=\"rust:3000\"}",
     "legendFormat": "{{color}}"
    }
   ]
  }
 ]
}