services:
  rust:
    image: counter_rust:latest
    networks:
      - main_net
      - shared_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    environment:
      - RUST_PORT=${RUST_PORT}
      - RUST_LOG=${RUST_LOG}
      - SVELTE_URL=${SVELTE_URL}
      - OTEL_ENDPOINT=${OTEL_ENDPOINT}

  svelte:
    image: counter_svelte:latest
    networks:
      - main_net
      - shared_net
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
    environment:
      - PORT=${SVELTE_PORT}
      - NODE_ENV=${NODE_ENV}

  caddy:
    image: caddy:latest
    networks:
      - main_net
    ports:
      - "80:80"
      - "443:443"
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
    environment:
      - CADDY_DOMAIN=${CADDY_DOMAIN}
      - RUST_NAME=${RUST_NAME}
      - RUST_PORT=${RUST_PORT}
      - SVELTE_NAME=${SVELTE_NAME}
      - SVELTE_PORT=${SVELTE_PORT}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - type: bind
        source: Caddyfile
        target: /etc/caddy/Caddyfile

networks:
  main_net:
    driver: overlay
  shared_net:
    external: true
    name: shared_net

volumes:
  caddy_data:
  caddy_config:

configs:
  caddy_config:
    file: Caddyfile
