services:
  rust:
    image: counter_rust:latest
    networks:
      - main_net
      - monitor_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    volumes:
      - ./saved_state.json:${RUST_STATE_PATH}
    logging:
      driver: loki
      options:
        mode: non-blocking
        loki-url: ${LOKI_URL}
        loki-batch-size: "10"
        loki-timeout: "10s"
        loki-retries: "3"
    environment:
      - RUST_PORT=${RUST_PORT}
      - RUST_LOG=${RUST_LOG}
      - SVELTE_URL=${SVELTE_URL}
      - RUST_STATE_PATH=${RUST_STATE_PATH}

  svelte:
    image: counter_svelte:latest
    networks:
      - main_net
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
    environment:
      - PORT=${SVELTE_PORT}
      - NODE_ENV=${NODE_ENV}

  caddy:
    image: caddy:2.9.1-alpine@sha256:b4e3952384eb9524a887633ce65c752dd7c71314d2c2acf98cd5c715aaa534f0
    networks:
      - main_net
    ports:
      - "80:80"
      - "443:443"
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
    logging:
      driver: loki
      options:
        mode: non-blocking
        loki-url: ${LOKI_URL}
        loki-batch-size: "10"
        loki-timeout: "10s"
        loki-retries: "3"
    environment:
      - CADDY_LOG_ROTATE_DAYS=356
      - CADDY_LOG_ROTATE_SIZE=10000
      - CADDY_DOMAIN=${CADDY_DOMAIN}
      - RUST_NAME=${RUST_NAME}
      - RUST_PORT=${RUST_PORT}
      - SVELTE_NAME=${SVELTE_NAME}
      - SVELTE_PORT=${SVELTE_PORT}
    volumes:
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./caddy_logs:/var/log/caddy
      - ./caddy_config/Caddyfile:/etc/caddy/Caddyfile

networks:
  main_net:
    driver: overlay
  monitor_net:
    external: true
    name: monitor_net
