services:
  grafana:
    image: grafana/grafana:10.4.1
    networks:
      - net
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1
    
  loki:
    image: grafana/loki:latest
    networks:
      - net
    ports:
      - "3100:3100"
    volumes:
      - loki_config:/config
      - type: bind
        source: loki_config.yml
        target: /etc/loki/loki_config.yml

networks:
  net:
    driver: overlay
    attachable: true
    internal: true

volumes:
  loki_config:

configs:
  loki_config:
    file: loki_config.yml
