services:
  grafana:
    image: grafana/grafana:10.4.1
    networks:
      - net
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1
    
  loki:
    image: grafana/loki:latest
    networks:
      - net
    ports:
      - "3100:3100"
    volumes:
      - ./loki_config.yml:/etc/loki/loki_config.yml
      - ./loki_data:/loki_data
    command: -config.file=/etc/loki/loki_config.yml
  
  prometheus:
    image: prom/prometheus:latest
    networks:
      - net
    volumes:
      - ./prometheus_config.yml:/etc/prometheus/prometheus_config.yml
      - ./prometheus_data:/prometheus_data
    command:
      - '--config.file=/etc/prometheus/prometheus_config.yml'
      - '--storage.tsdb.retention.time=1y'
      - '--storage.tsdb.path=/prometheus_data'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.wal-compression'
    deploy:
      placement:
        constraints: [node.role == manager]
  
networks:
  net:
    driver: overlay
    attachable: true
    internal: true
