auth_enabled: false

server:
  http_listen_port: 3100

common:
  instance_addr: 0.0.0.0
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
      replication_factor: 1

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 200
  max_retries: 5
  parallelise_shardable_queries: true

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
        tsdb:
          retention_period: 168h 

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  retention_enabled: true
  retention_delete_delay: 1h
  retention_delete_worker_count: 10

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp

analytics:
  reporting_enabled: false

limits_config:
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  max_query_parallelism: 128
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s
  chunk_cache_config:
    embedded_cache:
      enabled: true
      max_size_mb: 500
      ttl: 1h

frontend:
  max_outstanding_per_tenant: 2048
  compress_responses: true

log_level: warn
