global:
  scrape_interval: 15s
  evaluation_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'pickone-metrics'
    scheme: http
    metrics_path: '/metrics'
    static_configs:
      - targets: ['rust:3000']
    relabel_configs:
      - source_labels: [__param_target]
        target_label: instance
